f2=open("Myfile3.txt","w")
f2.write("I am good listner and speaker")
f2.close()
f2=open("Myfile3.txt","r")
print(f2.read())
f2.close()
f2=open("Myfile3.txt","a")
f2.write(" also good audience")
f2.close()
f2=open("Myfile3.txt","r")
print(f2.read())
f2.close()